apiVersion: v1
kind: Service
metadata:
  name: myproject-product-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: myproject-product-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000